title: "Hi, I'm Anton"
summary: "ğŸ‘¨â€ğŸ’» Coding - ğŸ—ºï¸ Travelling - ğŸ‚ Snowboarding - ğŸ“š Reading"

menu:
  About: pages/about
  Work: pages/work

max_post: 4

theme_color: 03adfc
theme_dark_color: fcbb17

favicon_ico: /favicon.ico
favicon: /favicon.png
favicon_apple: /apple-touch-icon.png
# Define path to user css
#(could be also located outside of theme)
# Relative to source/ directory
usercss: css/user.css

footer: true
github: bandantonio
linkedin: bandantonio
s_overflow: 11147608/anton-zolotukhin
medium: mister_gold

switch_light: lightbulb
switch_dark: lightbulb

article:
  thumbnail: true

disqus_enabled: false